# Generated by Django 4.2.5 on 2023-12-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimages',
            name='image',
            field=models.ImageField(default=None, max_length=350, null=True, upload_to=''),
        ),
    ]
