# Generated by Django 4.2.5 on 2023-12-24 08:57

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listingimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimages',
            name='image',
            field=models.ImageField(default=None, max_length=350, null=True, upload_to=listings.models.generate_filename),
        ),
    ]
